name: 'Build and Deploy Function App'
description: 'Builds and deploys a .NET Azure Function App'
inputs:
  AZURE_FUNCTIONAPP_PACKAGE_PATH:
    description: 'Path to the function app project'
    required: true
  AZURE_FUNCTIONAPP_NAME:
    description: 'Name of the Azure Function App'
    required: true
  AZURE_CREDENTIALS:
    description: 'Azure credentials for login'
    required: true
  DOTNET_VERSION:
    description: 'DotNet version to use'
    required: false
    default: '9.0.x'

outputs:
  functionPrincipalId:
    description: 'Principal ID of the Function App managed identity'
    value: ${{ steps.bicep_deployment.outputs.functionPrincipalId }}

runs:
  using: "composite"
  steps:
    - name: Setup DotNet ${{ inputs.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash # For Linux, use bash
      run: |
        pushd './${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Deploy Bicep file
      id: bicep_deployment
      uses: azure/arm-deploy@v2
      with:
        template: ./SqlManagedIdentity/Deployment/deploy.bicep
        failOnStdErr: false
        scope: 'subscription'
        region: 'Central US'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'         